# Generated by Django 4.2.13 on 2026-06-26 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('feed_url', models.URLField(blank=True, help_text='RSS/Atom feed URL if different from main URL', max_length=500, null=True)),
                ('region', models.CharField(choices=[('global', 'Global'), ('africa', 'Africa'), ('malawi', 'Malawi')], default='global', max_length=20)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('scrape', 'HTML Scrape'), ('api', 'REST API')], default='rss', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_new', models.PositiveIntegerField(default=0)),
                ('articles_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='scheduler', help_text='scheduler | manual | api', max_length=50)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_logs', to='articles.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('category', models.CharField(choices=[('clinical_nutrition', 'Clinical Nutrition'), ('dietetics', 'Dietetics Practice'), ('research', 'Research & Evidence'), ('public_health', 'Public Health Nutrition'), ('pediatric', 'Pediatric Nutrition'), ('malnutrition', 'Malnutrition & Wasting'), ('food_security', 'Food Security'), ('policy', 'Policy & Guidelines'), ('education', 'Nutrition Education'), ('other', 'Other')], default='other', max_length=30)),
                ('region', models.CharField(choices=[('global', 'Global'), ('africa', 'Africa'), ('malawi', 'Malawi')], default='global', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of keyword tags')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(default=0.0, help_text='0–1 keyword relevance score')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
            options={
                'ordering': ['-published_at', '-crawled_at'],
                'indexes': [models.Index(fields=['category'], name='articles_ar_categor_d8555e_idx'), models.Index(fields=['region'], name='articles_ar_region_4d1db6_idx'), models.Index(fields=['published_at'], name='articles_ar_publish_a51805_idx'), models.Index(fields=['source'], name='articles_ar_source__44296e_idx')],
            },
        ),
    ]
